version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: myuser
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # copy the initializations scripts to the container
    # COPY ./init.sql /docker-entrypoint-initdb.d/init.sql
    container_name: database

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   container_name: adminer